from enum import Enum

class ValidationStatus(str, Enum):

    AUTO_PASS = "AUTO_PASS"

    EOI_REQUIRED = "EOI_REQUIRED"

    MANUAL_REVIEW = "MANUAL_REVIEW"

    DATA_MISSING = "DATA_MISSING"

    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"

    NOT_APPLICABLE = "NOT_APPLICABLE"

    VALIDATION_WARNING = "VALIDATION_WARNING"
    